/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.np_project.client.view;

import rs.ac.bg.fon.np_project.client.thread.ServerStoppedListener;
import rs.ac.bg.fon.np_project.client.Client;
import rs.ac.bg.fon.np_project.client.communication.Communication;
import rs.ac.bg.fon.np_project.commonlibrary.communication.CurrentUser;
import rs.ac.bg.fon.np_project.client.controller.ControllerUI;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.np_project.commonlibrary.model.Worker;

/**
 *
 * @author Simona
 */
public class FrmMain extends javax.swing.JFrame {

    private Worker currentUser;
    /**
     * Creates new form FrmMain
     */
    public FrmMain(Worker currentUser) {
        initComponents();
        this.currentUser=currentUser;
        setTitle("Ravnica");
        txtUlogovanKorisnik.setText(CurrentUser.getCurrentUser().getUsername());
        txtUlogovanKorisnik.setEditable(false);
        FrameCenter.CenteredFrame(this);
        ImageIcon img = new ImageIcon("pozadina.jpg");

        lblPhoto.setIcon(img);
        addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                try {

                    ControllerUI.getInstance().logout(currentUser);
                    System.exit(0);

                } catch (Exception ex) {
                    System.out.println("Konekcija prekinuta.");
                       System.exit(0);
                }
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }

        });

        ControllerUI.getInstance().setServerStoppedListener(new ServerStoppedListener() {
            @Override
            public void serverStopped() {
                stop();
            }
        });
    }
    
    private void stop() {
        JOptionPane.showMessageDialog(this, "Konekcija sa serverom je prekinuta. Molimo Vas, pokušajte kasnije.", "Prekid konekcije", JOptionPane.ERROR_MESSAGE);
        this.dispose();

        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUlogovanKorisnik = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiPretragaClanova = new javax.swing.JMenuItem();
        jmiDodajClana = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiSveIgre = new javax.swing.JMenuItem();
        jmiDodajIgru = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiIznajmi = new javax.swing.JMenuItem();
        jmiRazduzi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel1.setText("Ulogovan korisnik");

        txtUlogovanKorisnik.setFont(new java.awt.Font("Sylfaen", 0, 13)); // NOI18N

        btnLogout.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnLogout.setText("Odjava");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Clanovi");
        jMenu1.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setMaximumSize(new java.awt.Dimension(150, 32767));
        jMenu1.setPreferredSize(new java.awt.Dimension(130, 24));

        jmiPretragaClanova.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jmiPretragaClanova.setText("Pretraga");
        jmiPretragaClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaClanovaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPretragaClanova);

        jmiDodajClana.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jmiDodajClana.setText("Dodaj");
        jmiDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajClanaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiDodajClana);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(204, 102, 255));
        jMenu2.setText("Igre");
        jMenu2.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jMenu2.setMaximumSize(new java.awt.Dimension(130, 32767));

        jmiSveIgre.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jmiSveIgre.setText("Pretraga");
        jmiSveIgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSveIgreActionPerformed(evt);
            }
        });
        jMenu2.add(jmiSveIgre);

        jmiDodajIgru.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jmiDodajIgru.setText(" Dodaj");
        jmiDodajIgru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajIgruActionPerformed(evt);
            }
        });
        jMenu2.add(jmiDodajIgru);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(204, 102, 255));
        jMenu3.setText("Opcije");
        jMenu3.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N

        jmiIznajmi.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jmiIznajmi.setText("Iznajmi igru");
        jmiIznajmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIznajmiActionPerformed(evt);
            }
        });
        jMenu3.add(jmiIznajmi);

        jmiRazduzi.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jmiRazduzi.setText("Razduzi igru");
        jmiRazduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRazduziActionPerformed(evt);
            }
        });
        jMenu3.add(jmiRazduzi);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(txtUlogovanKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUlogovanKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPretragaClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaClanovaActionPerformed

        new FrmUsers(this, true).setVisible(true);

    }//GEN-LAST:event_jmiPretragaClanovaActionPerformed

    private void jmiDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajClanaActionPerformed
        
        new FrmAddUser(this, true).setVisible(true);

    }//GEN-LAST:event_jmiDodajClanaActionPerformed

    private void jmiSveIgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSveIgreActionPerformed

        new FrmGames(this, true).setVisible(true);

    }//GEN-LAST:event_jmiSveIgreActionPerformed

    private void jmiDodajIgruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajIgruActionPerformed

        new FrmAddGame(this, true).setVisible(true);

    }//GEN-LAST:event_jmiDodajIgruActionPerformed

    private void jmiIznajmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIznajmiActionPerformed

        new FrmRentGame(this, true).setVisible(true); 

    }//GEN-LAST:event_jmiIznajmiActionPerformed

    private void jmiRazduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRazduziActionPerformed

        new FrmRestoreGame(this, true).setVisible(true); 

    }//GEN-LAST:event_jmiRazduziActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        try {
            Communication.getInstance().logout(currentUser);
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);

        }
        this.dispose();
        try {
            new Client().connect();
        } catch (IOException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiDodajClana;
    private javax.swing.JMenuItem jmiDodajIgru;
    private javax.swing.JMenuItem jmiIznajmi;
    private javax.swing.JMenuItem jmiPretragaClanova;
    private javax.swing.JMenuItem jmiRazduzi;
    private javax.swing.JMenuItem jmiSveIgre;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JTextField txtUlogovanKorisnik;
    // End of variables declaration//GEN-END:variables
}
